services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: attendance_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: employee_attendance
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_PASSWORD: password123
      MYSQL_USER: attendance_user
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - attendance_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Laravel Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: attendance_app
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - APP_NAME=AttendPro
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=employee_attendance
      - DB_USERNAME=attendance_user
      - DB_PASSWORD=password123
      - CACHE_DRIVER=database
      - SESSION_DRIVER=database
      - QUEUE_CONNECTION=database
      - MAIL_MAILER=log
    volumes:
      - app_storage:/var/www/html/storage
      - app_bootstrap:/var/www/html/bootstrap/cache
    ports:
      - "8000:80"
    networks:
      - attendance_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/health"]
      timeout: 10s
      retries: 3

  # phpMyAdmin (Optional - for database management)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: attendance_phpmyadmin
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: attendance_user
      PMA_PASSWORD: password123
    ports:
      - "8080:80"
    networks:
      - attendance_network

# Networks
networks:
  attendance_network:
    driver: bridge

# Volumes
volumes:
  mysql_data:
    driver: local
  app_storage:
    driver: local
  app_bootstrap:
    driver: local